### PR TITLE
Status command

### PR DESCRIPTION
**Pull request by islamelnabarawy**
This pull request creates an implementation for the status command that prints a formatted table.

It should satisfy issue #2 and possibly #14, maybe after some adjustments to which fields to show, etc...

This introduces 2 more dependencies, added to requirements.txt (prettytable and progressbar2).

**Note:** this was created after the changes from pull request #27 and should be merged after it to avoid merge conflicts.

### CODE REVIEW

**Comment by islamelnabarawy** [comment]
@LinuxMercedes I've been using the status command and it's working and very stable. It should be safe to merge this pull request if you would like to do so.

**Comment by tymorrow** [comment]
I looked through the diff for about a minute and as pedantic as it might come across, some of the changes gave me pause.
`assigner.py` has gotten lengthy (I guess... idk) and I'm just being "that guy" who is stressing the importance of being idiomatic, keeping the style in check, and not throwing out raised errors willy-nilly.

Any reasons for this are not obvious to me on the short glance I took, but a couple examples would be:
- the removal of some  `raise NotImplementedError` statements
- properties within the config parameter are not set to variables at the top of the function, but accessed multiple times

I'd say put this on hold for a bit longer until someone has time to really look it over.
I really didn't look for very long but would be happy to in the future.

**Comment by tymorrow** [comment]
Also if you added any third-party package dependencies, make sure they are added to `requirements.txt` if that's still a thing...

**Comment by islamelnabarawy** [comment]
@tymorrow Thanks for the comments! I'm definitely in favor of keeping the style in check and making sure the code is clean and consistent.

The `raise NotImplementedError` statements were removed because the `--student` option was implemented throughout the different commands. This probably doesn't belong in the same pull request as the status command, though... I thought it had already been merged earlier, but perhaps it wasn't and it accidentally got combined with this pull request due to the fact that I wasn't paying attention to which branch I was on one night and accidentally implemented that option on the master branch directly.

I'm inclined to suggest closing this pull request for now, and then taking the time to re-do the commit history properly such that things seem more organized and less hasty. I know the code runs fine and is well written and tested, but it was written in the spur of the moment, which may be reflected in the commits and style.

The code for the status command is on my fork, anyone is welcome to clone it and modify it as necessary, then create another pull request as you deem appropriate. I'm currently busy with several other projects, so I doubt I will have time to clean this up and re-create it any time soon. It might also be worth noting that I've been very happy with the tool's functionality as it stands on my fork right now, and I'm using it for CS1001 with great success.

Thanks!

**Comment by LinuxMercedes** [comment]
I vote leave it open--I haven't merged it just because I haven't taken the time to review it thoroughly. I will try to do that next week!

**Comment by LinuxMercedes** [comment]
Well, this took way too long to merge but I'm happy with it!

**Pull request merged**
